version: '3'

services:
  database:
    image: mysql:8.0
    restart: always
    environment:
    - MYSQL_DATABASE="test"
    - MYSQL_DATABASE_USER=root
    - MYSQL_DATABASE_PASSWORD=admin
    - MYSQL_ROOT_PASSWORD=admin
    ports:
    - 3306:3306
